// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AdjustNamespace
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAdjustNamespacePackageString = "19967834-2536-4a51-82f7-e607434734d2";
        public static Guid guidAdjustNamespacePackage = new Guid(guidAdjustNamespacePackageString);

        public const string guidAdjustNamespacePackageCmdSetString = "3f7538ed-5c20-4d49-89fc-c401bb76df25";
        public static Guid guidAdjustNamespacePackageCmdSet = new Guid(guidAdjustNamespacePackageCmdSetString);

        public const string guidImagesString = "6309e701-5f02-4bc7-8376-02ec55028dbf";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ExtensionMenuGroup = 0x201D;
        public const int ExtensionSubMenuGroup = 0x201E;
        public const int ExtensionSubMenu = 0x201F;
        public const int ExtensionSubMenuGroupService = 0x2020;
        public const int DoAdjustCommandId = 0x0300;
        public const int AdjustSolutionCommandId = 0x0301;
        public const int EditSkippedPathsCommandId = 0x0302;
        public const int order16 = 0x0001;
    }
}