using AdjustNamespace.Tests.Infrastructure;
using Xunit;
using static AdjustNamespace.Tests.Infrastructure.AdjustRunner;

namespace AdjustNamespace.Tests.Adjusting
{
    /// <summary>
    /// The features of C# 10 - 14 which write a type name at a new position or import a
    /// namespace in a new way. In every test <c>A.B.Cat</c> moves into <c>X.Y</c>.
    /// The extension members of C# 14 are in <c>CsAdjusterExtensionMemberTests</c>,
    /// the unions of C# 15 are in <c>CsAdjusterUnionTests</c>.
    /// </summary>
    public class CsAdjusterModernSyntaxTests
    {
        private const string CatBody =
@"namespace A.B
{
    public class Cat { }
}
";

        /// <summary>
        /// C# 10: the namespace is imported by a <c>global using</c> of another file and the
        /// moved type was the last one of it. The global clause names a namespace which does
        /// not exist anymore (CS0246) unless it is removed.
        /// </summary>
        [Fact]
        public async Task A_global_using_of_an_emptied_namespace_is_removed()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Cat.cs", CatBody)
                .AddDocument("MyApp", "GlobalUsings.cs",
@"global using A.B;
")
                .AddDocument("MyApp", "Consumer.cs",
@"namespace Other
{
    public class Consumer
    {
        public Cat Create() => new Cat();
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Cat.cs", "X.Y");

            Assert.Contains("using X.Y;", solution.TextOf("MyApp", "Consumer.cs"));
            Assert.DoesNotContain("A.B", solution.TextOf("MyApp", "GlobalUsings.cs"));
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// C# 10: the same, but the namespace keeps another type, so the global clause stays
        /// and the consumer gets a using clause of the target namespace.
        /// </summary>
        [Fact]
        public async Task A_global_using_of_a_living_namespace_stays()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Cat.cs", CatBody)
                .AddDocument("MyApp", "Dog.cs",
@"namespace A.B
{
    public class Dog { }
}
")
                .AddDocument("MyApp", "GlobalUsings.cs",
@"global using A.B;
")
                .AddDocument("MyApp", "Consumer.cs",
@"namespace Other
{
    public class Consumer
    {
        public Cat Create() => new Cat();

        public Dog Other() => new Dog();
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Cat.cs", "X.Y");

            Assert.Contains("using X.Y;", solution.TextOf("MyApp", "Consumer.cs"));
            Assert.Contains("global using A.B;", solution.TextOf("MyApp", "GlobalUsings.cs"));
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// .NET 6 implicit usings: a <c>&lt;Using Include="A.B" /&gt;</c> item of the project
        /// file becomes <c>global using global::A.B;</c> of a generated file in <c>obj</c>.
        /// That file is regenerated from the project file on every build, so it must not be
        /// edited; once the namespace is emptied the project does not compile (CS0246) until
        /// the item is removed from the project file, which the adjusting does not touch.
        ///
        /// So the file is not moved (<c>AdjustBlockKind.NamespaceImportedByProjectFile</c>),
        /// rather than the cleanup removing the clause from the generated file: the solution
        /// would compile right after the run and break on the next build. The consumer below
        /// needs nothing else, it sees the type through the generated clause.
        /// </summary>
        [Fact]
        public async Task A_namespace_imported_by_the_project_file_is_not_emptied_silently()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Cat.cs", CatBody)
                .AddDocument("MyApp", @"obj\Debug\net8.0\MyApp.GlobalUsings.g.cs",
@"// <auto-generated/>
global using global::A.B;
global using global::System;
")
                .AddDocument("MyApp", "Consumer.cs",
@"namespace Other
{
    public class Consumer
    {
        public Cat Create() => new Cat();
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Cat.cs", "X.Y");

            Assert.Contains("namespace A.B", solution.TextOf("MyApp", "Cat.cs"));
            Assert.Contains(
                "global using global::A.B;",
                solution.TextOf("MyApp", @"obj\Debug\net8.0\MyApp.GlobalUsings.g.cs")
                );
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// The same namespace keeps another type, so the generated clause stays valid and the
        /// file is moved as usual.
        /// </summary>
        [Fact]
        public async Task A_namespace_imported_by_the_project_file_which_stays_alive_is_left()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Cat.cs", CatBody)
                .AddDocument("MyApp", "Dog.cs",
@"namespace A.B
{
    public class Dog { }
}
")
                .AddDocument("MyApp", @"obj\Debug\net8.0\MyApp.GlobalUsings.g.cs",
@"// <auto-generated/>
global using global::A.B;
")
                .AddDocument("MyApp", "Consumer.cs",
@"namespace Other
{
    public class Consumer
    {
        public Cat Create() => new Cat();

        public Dog Other() => new Dog();
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Cat.cs", "X.Y");

            Assert.Contains("namespace X.Y", solution.TextOf("MyApp", "Cat.cs"));
            Assert.Contains("using X.Y;", solution.TextOf("MyApp", "Consumer.cs"));
            Assert.Contains(
                "global using global::A.B;",
                solution.TextOf("MyApp", @"obj\Debug\net8.0\MyApp.GlobalUsings.g.cs")
                );
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// C# 10: a lambda with an explicit return type.
        /// </summary>
        [Fact]
        public async Task A_lambda_return_type_is_fixed()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Cat.cs", CatBody)
                .AddDocument("MyApp", "Consumer.cs",
@"using A.B;

namespace Other
{
    public class Consumer
    {
        public object Short()
        {
            var make = Cat () => new Cat();
            return make;
        }

        public object Qualified()
        {
            var make = A.B.Cat () => new A.B.Cat();
            return make;
        }
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Cat.cs", "X.Y");

            var text = solution.TextOf("MyApp", "Consumer.cs");

            Assert.Contains("using X.Y;", text);
            Assert.Contains("X.Y.Cat () => new X.Y.Cat()", text);
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// C# 10: a record struct is moved as any other type. Its positional properties are
        /// <c>init</c> ones, which need <c>IsExternalInit</c> on .NET Framework.
        /// </summary>
        [Fact]
        public async Task A_record_struct_is_moved()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "IsExternalInit.cs",
@"namespace System.Runtime.CompilerServices
{
    public static class IsExternalInit { }
}
")
                .AddDocument("MyApp", "Point.cs",
@"namespace A.B
{
    public readonly record struct Point(int X, int Y);
}
")
                .AddDocument("MyApp", "Consumer.cs",
@"using A.B;

namespace Other
{
    public class Consumer
    {
        public Point Create() => new Point(1, 2) with { Y = 3 };
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Point.cs", "X.Y");

            Assert.Contains("using X.Y;", solution.TextOf("MyApp", "Consumer.cs"));
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// C# 11: a type argument of a generic attribute.
        /// </summary>
        [Fact]
        public async Task A_type_argument_of_a_generic_attribute_is_fixed()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Cat.cs", CatBody)
                .AddDocument("MyApp", "Consumer.cs",
@"using System;
using A.B;

namespace Other
{
    [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
    public class TaggedAttribute<T> : Attribute { }

    [Tagged<Cat>]
    [Tagged<A.B.Cat>]
    public class Consumer { }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Cat.cs", "X.Y");

            var text = solution.TextOf("MyApp", "Consumer.cs");

            Assert.Contains("using X.Y;", text);
            Assert.Contains("[Tagged<X.Y.Cat>]", text);
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// C# 11: a file-local type is moved together with its file, and the references to it
        /// can stand in that file only.
        /// </summary>
        [Fact]
        public async Task A_file_local_type_is_moved_with_its_file()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Cat.cs",
@"namespace A.B
{
    file class Helper
    {
        public static string Name => ""cat"";
    }

    public class Cat
    {
        public string Name => Helper.Name;
    }
}
")
                .AddDocument("MyApp", "Dog.cs",
@"namespace X.Y
{
    file class Helper { }

    public class Dog { }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Cat.cs", "X.Y");

            Assert.Contains("namespace X.Y", solution.TextOf("MyApp", "Cat.cs"));
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// C# 11: an ordinary type moves into a namespace which has a file-local type of the
        /// same name in another file. The file-local type is visible in its own file only,
        /// so the compiler accepts both of them, see
        /// <c>SubjectFileCollectorTests.A_file_local_type_of_the_same_name_is_no_conflict</c>.
        /// </summary>
        [Fact]
        public async Task An_ordinary_type_moves_next_to_a_file_local_one_of_the_same_name()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Helper.cs",
@"namespace A.B
{
    public class Helper { }
}
")
                .AddDocument("MyApp", "Dog.cs",
@"namespace X.Y
{
    file class Helper { }

    public class Dog
    {
        public object Make() => new Helper();
    }
}
")
                .AddDocument("MyApp", "Consumer.cs",
@"using A.B;

namespace Other
{
    public class Consumer
    {
        public Helper Create() => new Helper();
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Helper.cs", "X.Y");

            Assert.Contains("namespace X.Y", solution.TextOf("MyApp", "Helper.cs"));
            Assert.Contains("using X.Y;", solution.TextOf("MyApp", "Consumer.cs"));
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// C# 12: the parameters of a primary constructor and the arguments of the base type.
        /// </summary>
        [Fact]
        public async Task A_primary_constructor_and_its_base_call_are_fixed()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Cat.cs", CatBody)
                .AddDocument("MyApp", "Consumer.cs",
@"using A.B;

namespace Other
{
    public class Home<T>(T pet)
    {
        public T Pet => pet;
    }

    public class Shelter(Cat cat, A.B.Cat other) : Home<Cat>(cat)
    {
        public A.B.Cat Other => other;
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Cat.cs", "X.Y");

            var text = solution.TextOf("MyApp", "Consumer.cs");

            Assert.Contains("using X.Y;", text);
            Assert.DoesNotContain("A.B.Cat", text);
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// C# 12: an alias of any type, here an array and a tuple of a qualified type.
        /// The target of an alias is written with the full name, the other using clauses
        /// do not help it.
        /// </summary>
        [Fact]
        public async Task An_alias_of_any_type_is_fixed()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Cat.cs", CatBody)
                .AddDocument("MyApp", "Consumer.cs",
@"using CatArray = A.B.Cat[];
using CatPair = (A.B.Cat, int);
using NamedCatPair = (A.B.Cat Cat, int Count);

namespace Other
{
    public class Consumer
    {
        public CatArray All() => null;

        public CatPair Pair() => default;

        public NamedCatPair Named() => default;
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Cat.cs", "X.Y");

            var text = solution.TextOf("MyApp", "Consumer.cs");

            Assert.Contains("using CatArray = X.Y.Cat[];", text);
            Assert.Contains("using CatPair = (X.Y.Cat, int);", text);
            Assert.Contains("using NamedCatPair = (X.Y.Cat Cat, int Count);", text);
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// The runtime types a closed class is compiled with. They do not exist in the
        /// reference assemblies of net48, so they are declared as a source file, exactly as
        /// <see cref="TestSolution.UnionSupportBody"/> does it for the unions.
        /// <c>System.*</c> is a special namespace for the extension, so the file is never adjusted.
        /// </summary>
        private const string ClosedSupportBody =
@"namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class IsClosedTypeAttribute : Attribute
    {
    }

    [AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = false)]
    public sealed class CompilerFeatureRequiredAttribute : Attribute
    {
        public CompilerFeatureRequiredAttribute(string featureName)
        {
            FeatureName = featureName;
        }

        public string FeatureName { get; }
    }
}
";

        /// <summary>
        /// C# 15: a closed class (a preview feature, enabled here by
        /// <see cref="TestSolution.WithUnionSupport"/> which switches the language version).
        /// Its subclasses have to be declared in the same assembly, which the move does not
        /// change, and a switch over all of them is exhaustive without a discard.
        /// </summary>
        [Fact]
        public async Task A_closed_class_is_moved()
        {
            using var solution = new TestSolution()
                .WithUnionSupport()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Shape.cs",
@"namespace A.B
{
    public closed class Shape { }
}
")
                .AddDocument("MyApp", "Shapes.cs",
@"using A.B;

namespace Other
{
    public class Circle : Shape { }

    public class Square : Shape { }

    public static class ShapeNames
    {
        public static string Of(Shape shape) => shape switch
        {
            Circle => ""circle"",
            Square => ""square"",
        };
    }
}
")
                .AddDocument("MyApp", "ClosedSupport.cs", ClosedSupportBody)
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Shape.cs", "X.Y");

            var text = solution.TextOf("MyApp", "Shapes.cs");

            Assert.Contains("using X.Y;", text);
            Assert.DoesNotContain("using A.B;", text);
            Assert.Empty(await solution.CompilationErrorsAsync());
        }

        /// <summary>
        /// C# 14: an unbound generic type in <c>nameof</c>.
        /// </summary>
        [Fact]
        public async Task An_unbound_generic_type_in_nameof_is_fixed()
        {
            using var solution = new TestSolution()
                .AddProject("MyApp")
                .AddDocument("MyApp", "Box.cs",
@"namespace A.B
{
    public class Box<T> { }
}
")
                .AddDocument("MyApp", "Consumer.cs",
@"using A.B;

namespace Other
{
    public class Consumer
    {
        public string Short => nameof(Box<>);

        public string Qualified => nameof(A.B.Box<>);
    }
}
")
                ;

            Assert.Empty(await solution.CompilationErrorsAsync());

            await AdjustAndCleanupAsync(solution, "MyApp", "Box.cs", "X.Y");

            var text = solution.TextOf("MyApp", "Consumer.cs");

            Assert.Contains("using X.Y;", text);
            Assert.Contains("nameof(X.Y.Box<>)", text);
            Assert.Empty(await solution.CompilationErrorsAsync());
        }
    }
}
