//The shared project declares its global usings in AdjustNamespacePackage.cs, which is excluded
//from this project (it depends on the code generated by the VSIX project), so they are repeated here.
//Keep this file in sync with the header of AdjustNamespace.VsixShared\AdjustNamespacePackage.cs.
global using Community.VisualStudio.Toolkit;
global using Microsoft.VisualStudio.Shell;
global using System;
global using Task = System.Threading.Tasks.Task;
